CREATE TABLE ANUNCIANTE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    CPF CHAR(11) UNIQUE,
    EMAIL VARCHAR(50) UNIQUE,
    SENHA_HASH VARCHAR(255),
    TELEFONE CHAR(11),
)ENGINE=InnoDB;

CREATE TABLE ANUNCIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(50),
    MODELO VARCHAR(50),
    ANO INT,
    QUILOMETRAGEM FLOAT,
    DESCRICAO TEXT,
    VALOR FLOAT,
    DATA_HORA DATETIME,
    ESTADO CHAR(2),
    CIDADE VARCHAR(50),
    ID_ANUNCIANTE INT NOT NULL,
    FOREIGN KEY (ID_ANUNCIANTE) REFERENCES ANUNCIANTE(ID) ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE INTERESSE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    TELEFONE CHAR(11),
    MENSAGEM TEXT,
    DATA_HORA DATETIME,
    ID_ANUNCIO INT NOT NULL,
    FOREIGN KEY (ID_ANUNCIO) REFERENCES ANUNCIO(ID) ON DELETE CASCADE
)

CREATE TABLE FOTO (
    NOME_FOTO VARCHAR(50),
    ID_ANUNCIO INT NOT NULL,
    FOREIGN KEY (ID_ANUNCIO) REFERENCES ANUNCIO(ID) ON DELETE CASCADE,
)